general:
    name: 'protein_dit'
    gpus: 1
    save_model: True

model:
    hidden_size: 256
    depth: 6
    num_heads: 8
    mlp_ratio: 4
    drop_condition: 0.1
    diffusion_steps: 100  # Reduced for faster training
    diffusion_noise_schedule: 'cosine'

train:
    n_epochs: 1000
    batch_size: 16
    lr: 0.0002
    weight_decay: 1e-5
    num_workers: 4
    val_check_interval: 1.0  # Validate every epoch

dataset:
    datadir: 'data/protein_train'
    task_name: 'alphafold_train'
    pin_memory: True 